print ("==========================================================================================")
print ("BIODATA")
print ("==========================================================================================")
print ("Nama : Deriana Maruf")
print ("Kelas : X PPLG 1")
print ("Gender : Laki Laki")
print ("Alamat : Jawa Barat,Cianjur,Cugenang,Cibulakan,Kp.Babakan Imbangan Pentas, Rt 01 Rw 03")
print ("===========================================================================================")